<?php

/*$card = array ('title' => array ('cayde_statue' => '',
                                  'oryxFunkoPop' => '',
                                  'gjallahorn' => '',
                                  'tenebrion' => '',
                                  'atheonFunkoPop' => '',
                                  'atheon' => '',
                                  'tshirt' => '',
                                  'chest' => '',
                                  'ghost' => '',),
              'alt' => array ('cayde_statue' => '',
                                  'oryxFunkoPop' => '',
                                  'gjallahorn' => '',
                                  'tenebrion' => '',
                                  'atheonFunkoPop' => '',
                                  'atheon' => '',
                                  'tshirt' => '',
                                  'chest' => '',
                                  'ghost' => '',),
              'picture' => array ('cayde_statue' => '',
                                  'oryxFunkoPop' => '',
                                  'gjallahorn' => '',
                                  'tenebrion' => '',
                                  'atheonFunkoPop' => '',
                                  'atheon' => '',
                                  'tshirt' => '',
                                  'chest' => '',
                                  'ghost' => '',),
                                  'description' => array ('cayde_statue' => '',
                                  'oryxFunkoPop' => '',
                                  'gjallahorn' => '',
                                  'tenebrion' => '',
                                  'atheonFunkoPop' => '',
                                  'atheon' => '',
                                  'tshirt' => '',
                                  'chest' => '',
                                  'ghost' => '',),
              'descriptionList' => array ('cayde_statue' => '',
                                  'oryxFunkoPop' => '',
                                  'gjallahorn' => '',
                                  'tenebrion' => '',
                                  'atheonFunkoPop' => '',
                                  'atheon' => '',
                                  'tshirt' => '',
                                  'chest' => '',
                                  'ghost' => '',),
              'minPic1' => array ('cayde_statue' => '',
                                  'oryxFunkoPop' => '',
                                  'gjallahorn' => '',
                                  'tenebrion' => '',
                                  'atheonFunkoPop' => '',
                                  'atheon' => '',
                                  'tshirt' => '',
                                  'chest' => '',
                                  'ghost' => '',),
              'minPic2' => array ('cayde_statue' => '',
                                  'oryxFunkoPop' => '',
                                  'gjallahorn' => '',
                                  'tenebrion' => '',
                                  'atheonFunkoPop' => '',
                                  'atheon' => '',
                                  'tshirt' => '',
                                  'chest' => '',
                                  'ghost' => '',),
              'price' => array ('cayde_statue' => '',
                                  'oryxFunkoPop' => '',
                                  'gjallahorn' => '',
                                  'tenebrion' => '',
                                  'atheonFunkoPop' => '',
                                  'atheon' => '',
                                  'tshirt' => '',
                                  'chest' => '',
                                  'ghost' => '',),
)
*/
// $nomDuTableau = array ('title' => ' ', 'alt' => '', 'picture' => 'assets/img/ ', 
// 'description' => ' ', 
// 'descriptionList' => '', 'minPic1' => 'assets/img/ ', 'minPic2' => 'assets/img/ ', 'price' => '€');  
 $cardCaydeStatue = array('title' => 'Statue de Cayde-6', 'alt' => 'Photo d\'une statue de Cayde-6', 'picture' => 'assets/img/cayde_statue.png',
  'description' => 'La statue de Cayde-6 lors de son dernier combat.',
  'descriptionList' => 'Matériaux : P.V.C <br /> Hauteur : 25 cm <br /> Largeur : 19 cm <br /> Profondeur : 12 cm', 'minPic1' => 'assets/img/cayde_statue1.png', 'minPic2' => 'assets/img/cayde_statue2.png', 'price' => '44.99 €');
  $cardOryxFunkoPop = array('title' => 'Figurine Oryx FunKo Pop!', 'alt' => 'Photo d\'une figurine funko_pop d\'Oryx', 'picture' => 'assets/img/funkopop_oryx.jpg',
  'description' => 'Figurine du Roi des Corrompus Oryx en vinyle.',
  'descriptionList' => 'Matériaux : vinyle <br /> Poids : 200 g <br /> Dimensions : 6.4 x 6.4 x 9.5 cm', 'minPic1' => 'assets/img/funkop_oryx1.jpg', 'minPic2' => 'assets/img/funkopop_oryx2.jpg', 'price' => '8 €');
  $cardGjallahorn = array('title' => 'Iron Gjallahorn MacFarlane', 'alt' => 'Photo de l\'Iron Gjallahorn', 'picture' => 'assets/img/gjallahorn_toy.jpg',
  'description' => 'LE lance-roquette emblématique de Destiny.',
  'descriptionList' => 'Dimension : environ 1.20 m <br /> Inclus effets sonores, batteries vendues séparémment, support non fourni', 'minPic1' => 'assets/img/gjallahorn_toy1.jpg', 'minPic2' => 'assets/img/gjallahorn_toy2.jpg', 'price' => '145.99 €');
  $cardAtheonFunkoPop = array ('title' => 'Figurine Athéon FunKo Pop!', 'alt' => 'Photo d\'une figurine funko_pop d\'Athéon', 'picture' => 'assets/img/funkopop_atheon.jpg',
  'description' => 'Figurinedu Gardien du Caveau de Verre, emballé dans une boîte à fenêtre illustrée.',
  'descriptionList' => 'Matériaux : vinyle <br /> Poids : 200 g <br /> Dimensions : 6.4 x 6.4 x 9.5 cm', 'minPic1' => 'assets/img/funkopop_atheon2.jpg', 'minPic2' => '', 'price' => '8 €');
  $cardTenebrion =  array ('title' => 'Ténébrion Méga-blocks', 'alt' => 'Ténébrion Déchus', 'picture' => 'assets/img/tenebrion_megablock.jpg',
  'description' => 'Ténébrion Déchus à assembler, pattes articulées, tourrelle rotative...',
  'descriptionList' => 'Contient un ténébrion, un Gardien et un Capitaine déchus, un collecteur.', 'minPic1' => 'assets/img/tenebrion_megablock1.jpg', 'minPic2' => 'assets/img/tenebrion_megablock2.jpg', 'price' => '29.95 €');
  $cardAtheon = array ('title' => 'Méga-block Athéon ', 'alt' => 'Atheon Méga-block', 'picture' => 'assets/img/atheon_megablock.jpg',
  'description' => 'Athéon (Gardien du Caveau de Verre) avec harpie à assembler, articulé,  ',
  'descriptionList' => 'Contiens Atheon, une harpie et un Gardien (Arcaniste), armes et armures amovibles', 'minPic1' => 'assets/img/atheon_megablock1.jpg', 'minPic2' => 'assets/img/atheon_megablock1.jpg ', 'price' => '21.19 €');
  $cardTshirt = array ('title' => 'T-shirt Cayde et Uldren', 'alt' => 'Photo des T-shirt Cayde-6 et Uldren Sov', 'picture' => 'assets/img/pack_tshirt.png',
  'description' => 'Pack de 2 T-shirt "For Cayde" et "Get Uldren", logo Destiny 2 : Renégats imprimé au dos, disponible du XS au 3-XL.',
  'descriptionList' => 'Composition : 50 % polyester, 50% cotton', 'minPic1' => 'assets/img/pack_tshirt_back.png ', 'minPic2' => '', 'price' => '38.99 €');
  $cardChest = array ('title' => 'Jeu d\'échec Destiny 2', 'alt' => 'Jeu d\'échec Destiny', 'picture' => 'assets/img/destiny_chest.png',
  'description' => 'Jeu d\'échec Destiny, sculpté par des artistes de Bungie et de Bigshop Toywork et regroupant les héros de la saga Destiny, parmis Osiris, Ghaul, Mara Sov, et bien d\'autres.',
  'descriptionList' => '', 'minPic1' => 'assets/img/destiny_chest2.png ', 'minPic2' => '', 'price' => '68.99 €');
  $cardGhost = array ('title' => 'Coque des frags vinyle', 'alt' => 'Photo d\'un spectre orange et bleu', 'picture' => 'assets/img/ghost.jpg ',
  'description' => 'Reproduction en vynile de la coque des frags.',
  'descriptionList' => 'Vendue avec un code permettant de récupérer l\'emblème "carrhae" dans le jeu Destiny 2', 'minPic1' => 'assets/img/ghost_front.jpg ', 'minPic2' => 'assets/img/ghost_side.jpg ', 'price' => '36.99 €');
  $card = array($cardCaydeStatue, $cardOryxFunkoPop, $cardGjallahorn, $cardAtheonFunkoPop, $cardTenebrion, $cardAtheon, $cardTshirt, $cardChest, $cardGhost);



